// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF86AkttlCKEvQZrFV4nZjz2mThcLNK0E',
    appId: '1:969531684952:web:d8392cfcd027fed93e722d',
    messagingSenderId: '969531684952',
    projectId: 'whatsapp-messengr-cc8d1',
    authDomain: 'whatsapp-messengr-cc8d1.firebaseapp.com',
    storageBucket: 'whatsapp-messengr-cc8d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4HqtxLIAt8CCrcncQCKtZ5oFETMDiMWA',
    appId: '1:969531684952:android:667dea0049e4b38f3e722d',
    messagingSenderId: '969531684952',
    projectId: 'whatsapp-messengr-cc8d1',
    storageBucket: 'whatsapp-messengr-cc8d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXtg4EBd4QZwsSdwfsUc8ZWe521okvj74',
    appId: '1:969531684952:ios:f6424d279d3adb6f3e722d',
    messagingSenderId: '969531684952',
    projectId: 'whatsapp-messengr-cc8d1',
    storageBucket: 'whatsapp-messengr-cc8d1.appspot.com',
    iosBundleId: 'com.example.whatsappClon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXtg4EBd4QZwsSdwfsUc8ZWe521okvj74',
    appId: '1:969531684952:ios:bada3e6838bf9f123e722d',
    messagingSenderId: '969531684952',
    projectId: 'whatsapp-messengr-cc8d1',
    storageBucket: 'whatsapp-messengr-cc8d1.appspot.com',
    iosBundleId: 'com.example.whatsappClon.RunnerTests',
  );
}
